### ISSUE TITLE
Trouble compiling

### ISSUE THREAD

**Issue by CaydendW** [tyler569/nightingale#25]
Sorry if I am missing something but I ran the toolchain script in a place that was in path. The compiler runs perfectly but when I run `make` it returns:
```
make -j 8 -C . INNER=1 ngos.iso
make[1]: Entering directory '/home/cayden/Documents/Code/Kernel/nightingale'
CC      syscall.o
CC      errno.o
CC      vector.o
CC      syscalls.o
CC      stdlib.o
CC      locale.ox86_64-nightingale-gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory

compilation terminated.
x86_64-nightingale-gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.
make[1]: *** [makefile.inc:18: build-x86_64/libc/syscall.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [makefile.inc:23: build-x86_64/libc/errno.o] Error 1
x86_64-nightingale-gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.
make[1]: *** [makefile.inc:28: build-x86_64/libc/vector.o] Error 1
x86_64-nightingale-gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.
make[1]: *** [makefile.inc:33: build-x86_64/libc/syscalls.o] Error 1
x86_64-nightingale-gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.
make[1]: *** [makefile.inc:38: build-x86_64/libc/stdlib.o] Error 1
x86_64-nightingale-gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.
make[1]: *** [makefile.inc:43: build-x86_64/libc/locale.o] Error 1
make[1]: Leaving directory '/home/cayden/Documents/Code/Kernel/nightingale'
make: *** [makefile:2: all] Error 2
```
What am I missing? 
Thank you in advance.

**Comment by tyler569** [comment]
Hi! Thanks for your interest in the project!

I suspect you put the compiler itself in your path, but that it can't find the associated programs it needs, `cc1` is a component of gcc that the compiler executes.

The way I have the `build_toolchain` script set up right now, it's assuming you just add `~/.local/bin` to your path - if that folder exists you could try that first to see if it makes a difference.


And just to make sure - the toolchain script should be run where it is in the repo - it has to get the path to the repo to set the sysroot in the compiler (`SYSROOT=$(realpath ../sysroot)`), if you moved it out to somewhere on the path first I'm not sure what would happen.

If none of that helps, could you send me the output of a few commands?
```
 $ echo "int main() {}" > test.c
 $ x86_64-nightingale-gcc -v test.c

 $ x86_64-nightingale-gcc --print-search-dirs

 $ x86_64-nightingale-gcc --print-prog-name=cc1
```

That should help make it more clear what's happening.
Whatever it ends up being, I'll make sure to update the script or the docs so it's more clear!

**Comment by CaydendW** [comment]
Thank You for being so considerate. Me (Being an idiot) copied the files to /bin. Didn't know that extra things might be needed. I will mark this issue as closed. Thank you for being understanding.
