### ISSUE TITLE
hello ,can i become a contributions and worker with your team toghter

### ISSUE THREAD

**Issue by felix0080** [tyler569/nightingale#26]
I'm interested in OS

**Comment by PabloDons** [comment]
Joining our team as a contributor and worker is a very sophisticated process. You need to be qualified for the position as we expect a very high level of education and at least 5 years of experience in the OS field. Would you be so kind as to provide us with your resume? we will get back to you as soon as we have reviewed it. Then hopefully, we will call you for an interview!

sincerely, tyler569 co. OS Development Center

**Comment by felix0080** [comment]
I am very happy, I would like to do these things, thank you for your reply
